version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'UTC'
      WEBPASSWORD: '${WEBPASSWORD:-admin}'
      DNS1: '${DNS1:-1.1.1.1}'
      DNS2: '${DNS2:-1.0.0.1}'
      VIRTUAL_HOST: '${VIRTUAL_HOST:-adblock.yourdomain.com}'
      LETSENCRYPT_HOST: '${VIRTUAL_HOST:-adblock.yourdomain.com}'
      LETSENCRYPT_EMAIL: '${LETSENCRYPT_EMAIL:-admin@yourdomain.com}'
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      - adblock-network

networks:
  adblock-network:
    driver: bridge